### ISSUE TITLE
Shall there be a mode to switch it to `proc_macro2`

### ISSUE THREAD

**Issue by vi** [parasyte/myn#7]
Shall `myn` have testing-oriented mode (as a `RUSTFLAGS` feature, crate feature or a separate `myn-proc-macro2` crate) where `proc_macro2` is used instead of direct `proc_macro`, so that users of the crate have both have testability for dev mode and independence on `proc_macro2`'s compile speed for prod mode?

**Comment by parasyte** [comment]
I haven't considered that! It's worth an exploration. It seems like it would be trivial to prototype, since `proc_macro2` types mirror the `proc_macro` types. I agree it would be very useful for testing.

**Comment by vi** [comment]
Looks like this approach aids testability of `myn` itself, but not testability of users of `myn` such as `onlyerror`, if I understand the patch correctly.
Other crates depending on `myn` should also have advantage of test mode vs prod mode split.

**Comment by parasyte** [comment]
That is a good point and something that I overlooked. I have added a feature flag for it in #9 to allow external crates to use `myn` in their own tests.
